### ISSUE TITLE
java.lang.ClassNotFoundException: io.grpc.examples.helloworld.GreeterGrpc

### ISSUE THREAD

**Issue by kwansikkim** [zalopay-oss/jmeter-grpc-plugin#2]
Dear All,

I've tried to use jmeter-grpc-plugin and faced issue below.
* Environment: 
  - server: ./build/install/examples/bin/hello-world-server(Nothing changed)
  - proto: helloworld.proto(Nothing changed)
-------------------------------------------------------------------------------------------------------------
2020-04-03 05:04:47,337 INFO v.z.j.g.c.GrpcClientSampler: Created GrpcClientSampler
2020-04-03 05:04:47,341 INFO v.z.j.g.c.GrpcClientSampler: Created GrpcClientSampler
2020-04-03 05:04:47,380 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2020-04-03 05:04:47,381 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-04-03 05:04:47,385 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2020-04-03 05:04:47,676 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2020-04-03 05:04:47,676 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2020-04-03 05:04:47,677 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2020-04-03 05:04:47,677 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2020-04-03 05:04:47,677 INFO v.z.j.g.c.GrpcClientSampler: Created GrpcClientSampler
2020-04-03 05:04:47,678 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2020-04-03 05:04:47,679 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2020-04-03 05:04:47,683 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2020-04-03 05:04:47,711 ERROR v.z.j.g.c.GrpcClientSampler: Call initGrpcClient has thrown an exception: 
java.lang.ClassNotFoundException: io.grpc.examples.helloworld.GreeterGrpc
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at vn.zalopay.jmeter.grpc.utils.GrpcUtils.getBlockingStub(GrpcUtils.java:193) ~[jmeter-grpc-client-sampler.jar:?]
	at vn.zalopay.jmeter.grpc.client.GrpcClientSampler.initGrpcClient(GrpcClientSampler.java:57) [jmeter-grpc-client-sampler.jar:?]
	at vn.zalopay.jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:69) [jmeter-grpc-client-sampler.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) [ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-04-03 05:04:47,713 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'GrpcClientSampler'.
java.lang.NullPointerException: null
	at vn.zalopay.jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:72) ~[jmeter-grpc-client-sampler.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) [ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-04-03 05:04:47,713 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2020-04-03 05:04:47,714 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2020-04-03 05:04:47,716 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-04-03 05:04:47,716 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)
-------------------------------------------------------------------------------------------------------------

Could you let me know how to resolve this issue?

Sincerely,

**Comment by thoainguyen** [comment]
Hi @kwansikkim, please verify that your jmeter that recognied the dependency by :
Copy the jar file after build the `*.proto` to `path/to/jmeter/lib/ext` before you run, if you continuosly get stuck, see more in [example](https://github.com/zalopay-oss/jmeter-grpc-plugin/tree/master/docs/example)
