### ISSUE TITLE
Jmeter -GRPC -Issue

### ISSUE THREAD

**Issue by sravanesr** [zalopay-oss/jmeter-grpc-plugin#5]
Hi Team -Thanks for code.

I had followed same steps and able to enable GRPC protocol in Jmeter.

Now my issues is ,I am unable to run GRPC sampler which you mentioned getting attached issue. Can you please help me here. Please find attachment 

[POC_GRPC.pdf](https://github.com/zalopay-oss/jmeter-grpc-plugin/files/4627756/POC_GRPC.pdf)

**Error message**

2020-05-14 11:36:42,759 ERROR v.z.j.g.u.GrpcUtils: Failed to load metadata: 
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Bearer': was expecting ('true', 'false' or 'null')
 at [Source: (String)"{"Authorization": Bearer Token"}"; line: 1, column: 25]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[jackson-core-2.9.10.jar:2.9.10]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703) ~[jackson-core-2.9.10.jar:2.9.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853) ~[jackson-core-2.9.10.jar:2.9.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899) ~[jackson-core-2.9.10.jar:2.9.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:968) ~[jackson-core-2.9.10.jar:2.9.10]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:500) ~[jackson-databind-2.9.10.jar:2.9.10]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364) ~[jackson-databind-2.9.10.jar:2.9.10]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29) ~[jackson-databind-2.9.10.jar:2.9.10]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014) ~[jackson-databind-2.9.10.jar:2.9.10]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005) ~[jackson-databind-2.9.10.jar:2.9.10]
	at vn.zalopay.jmeter.grpc.utils.GrpcUtils.createHeaderMap(GrpcUtils.java:123) [jmeter-grpc-client-sampler.jar:?]
	at vn.zalopay.jmeter.grpc.utils.GrpcUtils.getChannel(GrpcUtils.java:150) [jmeter-grpc-client-sampler.jar:?]
	at vn.zalopay.jmeter.grpc.client.GrpcClientSampler.initGrpcClient(GrpcClientSampler.java:76) [jmeter-grpc-client-sampler.jar:?]
	at vn.zalopay.jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:89) [jmeter-grpc-client-sampler.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) [ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2020-05-14 11:36:42,871 ERROR v.z.j.g.c.GrpcClientSampler: Call initGrpcClient has thrown an exception: 
java.lang.ClassNotFoundException: io.grpc.examples.helloworld.GreeterGrpc

**Comment by thoainguyen** [comment]
Hi @sravanesr, you lacked a quote in the **metaData** 
**INCORRECT**:  {"Authorization": Bearer Token"}
**CORRECT**: {"Authorization": "Bearer Token"} 
Best regrard 
Thoai Nguyen

**Comment by sravanesr** [comment]
Hi Thoai Nguyen -Thanks for quick response.
I tried with your suggestions,but still it is not working.Please find the attached screenshot.

[POc2.pdf](https://github.com/zalopay-oss/jmeter-grpc-plugin/files/4633637/POc2.pdf)

Appreciate for your quick response.

**Comment by sravanesr** [comment]
I tried to executed hello.jmx which is present in GRPC -plugin folder and again got same issue.Please find the attached screenshot.
[Poc3.pdf](https://github.com/zalopay-oss/jmeter-grpc-plugin/files/4634793/Poc3.pdf)

Error:
2020-05-15 14:57:19,884 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Hello World'.
java.lang.NullPointerException: null
	at vn.zalopay.jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:92) ~[jmeter-grpc-client-sampler.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) [ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2020-05-15 14:57:19,884 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Hello World'.
java.lang.NullPointerException: null
	at vn.zalopay.jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:92) ~[jmeter-grpc-client-sampler.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) ~[ApacheJMeter_core.jar:5.2.1]

**Comment by thoainguyen** [comment]
Hi @sravanesr, sorry for the late response
The plugin requires two things to run :

* [x] A .jmx file (seemly the above .jmx file is OK) 
* [ ] A .jar is packaged from *.proto file, you can archive it by follow
   2.1) go to folder docs/example/grpc-lib in repository
   2.2) put the hello.proto into src/main/proto
   2.3) execute command `mvn clean install`
   2.4) move grpc-lib-0.0.1.jar to {jmeter_home}/lib/ext

Best regard 
Thoai nguyen

**Comment by sravanesr** [comment]
Hi Thoai Nguyen -
I had done above steps but got different Jar generated .Below jar I got it
jmeter-grpc-client-sampler.Jar.. 
But not able to get  grpc-lib-0.0.1.jar.Please find the attachment.Please suggest me on this.
[Poc4.pdf](https://github.com/zalopay-oss/jmeter-grpc-plugin/files/4638621/Poc4.pdf)

**Comment by thoainguyen** [comment]
May you executed command `mvn clean install` outside the directory docs/examle/grpc-lib ?
