### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class proto.SigningProto

### ISSUE THREAD

**Issue by Bhala1987** [zalopay-oss/jmeter-grpc-plugin#7]
I am getting the following error, please let me know what may be wrong:

2020-05-27 18:06:21,909 INFO j.g.c.GrpcClientSampler: Created GrpcClientSampler
2020-05-27 18:06:21,910 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2020-05-27 18:06:21,910 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-05-27 18:06:21,912 INFO o.a.j.t.TestPlan: added C:\Users\b.rajalakshmi\Downloads\apache-jmeter-5.2.1\lib\ext\bcprov-jdk15on-1.60.jar to classpath
2020-05-27 18:06:21,912 INFO o.a.j.t.TestPlan: added C:\Users\b.rajalakshmi\Downloads\apache-jmeter-5.2.1\lib\ext\grpc-api-1.29.0.jar to classpath
2020-05-27 18:06:21,912 INFO o.a.j.t.TestPlan: added C:\Users\b.rajalakshmi\Downloads\apache-jmeter-5.2.1\lib\ext\grpc-netty-1.29.0.jar to classpath
2020-05-27 18:06:21,912 INFO o.a.j.t.TestPlan: added C:\Users\b.rajalakshmi\Downloads\apache-jmeter-5.2.1\lib\ext\grpc-netty-shaded-1.29.0.jar to classpath
2020-05-27 18:06:21,912 INFO o.a.j.t.TestPlan: added C:\Users\b.rajalakshmi\Downloads\apache-jmeter-5.2.1\lib\ext\grpc-okhttp-1.29.0.jar to classpath
2020-05-27 18:06:21,913 INFO o.a.j.t.TestPlan: added C:\Users\b.rajalakshmi\Downloads\apache-jmeter-5.2.1\lib\ext\jmeter-grpc-plugin.jar to classpath
2020-05-27 18:06:21,913 INFO o.a.j.t.TestPlan: added C:\Users\b.rajalakshmi\Downloads\apache-jmeter-5.2.1\lib\ext\lombok-1.18.10.jar to classpath
2020-05-27 18:06:21,913 INFO o.a.j.t.TestPlan: added C:\Users\b.rajalakshmi\Documents\Bhala\EHRData\bitbucket\jmeter\src\main\resources\config.properties to classpath
2020-05-27 18:06:21,913 INFO o.a.j.t.TestPlan: added C:\Users\b.rajalakshmi\Documents\Bhala\EHRData\bitbucket\jmeter\src\main\resources\jmeter\grpc\utils\GrpcClientSamplerResources.properties to classpath
2020-05-27 18:06:21,913 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2020-05-27 18:06:22,040 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2020-05-27 18:06:22,040 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2020-05-27 18:06:22,040 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2020-05-27 18:06:22,040 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2020-05-27 18:06:22,040 INFO j.g.c.GrpcClientSampler: Created GrpcClientSampler
2020-05-27 18:06:22,041 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2020-05-27 18:06:22,041 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2020-05-27 18:06:22,042 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2020-05-27 18:06:22,213 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2020-05-27 18:06:22,213 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[Thread Group 1-1,6,main]
java.lang.NoClassDefFoundError: Could not initialize class proto.SigningProto
	at proto.GetPublicKeyRequest.internalGetFieldAccessorTable(GetPublicKeyRequest.java:212) ~[jmeter-grpc-plugin.jar:?]
	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133) ~[jmeter-grpc-plugin.jar:?]
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:344) ~[jmeter-grpc-plugin.jar:?]
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:334) ~[jmeter-grpc-plugin.jar:?]
	at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:519) ~[jmeter-grpc-plugin.jar:?]
	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:111) ~[jmeter-grpc-plugin.jar:?]
	at jmeter.grpc.client.ClientRecorder.<init>(ClientRecorder.java:14) ~[jmeter-grpc-plugin.jar:?]
	at jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:88) ~[jmeter-grpc-plugin.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) ~[ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
2020-05-27 18:06:22,214 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-05-27 18:06:22,215 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

please find attached the screenshot of jmeter and the JAR file used for reference.
[jmeter-grpc-plugin.zip](https://github.com/zalopay-oss/jmeter-grpc-plugin/files/4690318/jmeter-grpc-plugin.zip)
![issue](https://user-images.githubusercontent.com/29075298/83051068-6079bd00-a045-11ea-917c-5ed09b3aecba.JPG)

**Comment by thoainguyen** [comment]
Hi @Bhala1987,
Might you forget type `import proto.SigninProto;` line in requestBuilderCode ?
Please attach the jmx file for detailed

**Comment by Bhala1987** [comment]
Thanks a lot @thoainguyen for getting back to me, I fixed it by adding the missing proto class for descriptor in the request :)
